Pages/Bonds.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CorporateFinance
{
    public class BondsModel : PageModel
    {
        
        // Functions
        public string Mode { get; set; }
        public void OnGetSimple()
        {
            Mode = "SBPV";
            

        }

        public void OnGetETD()
        {
            Mode = "ETD";
            
        }


        [BindProperty]
        public double ParValue { get; set; }

        [BindProperty]
        public double CouponRate { get; set; }
        
        [BindProperty]
        public double DiscountRate { get; set; }


        [BindProperty]
        public double YearsToMaturity { get; set; }

        public double AnuPV { get; set; }
        public double ParPV { get; set; }

        public double BondValue { get; set; }


        // SECOND SET

        [BindProperty]
        public double currentBondPrice { get; set; }
        [BindProperty]
        public double BFV { get; set; }
        [BindProperty]
        public int YtM { get; set; }
        [BindProperty]
        public double ACR { get; set; }
        [BindProperty]
        public int numberOfPaymentsPerYear { get; set; }

        public double YTM { get; set; }
        public double YTM_2 { get; set; }
        public void OnGet()
        {
            BondValue = 0;

        }

        public void OnPost()
        {
            


        }

        public void OnPostSimpleDone()
        {
            double presentValue = ParValue / Math.Pow(1 + DiscountRate, YearsToMaturity);
            double couponPayment = ParValue * CouponRate;
            double annuityPresentValue = (couponPayment * (1 - 1 / Math.Pow(1 + DiscountRate, YearsToMaturity))) / DiscountRate;
            AnuPV = annuityPresentValue;
            ParPV = presentValue;
            BondValue = annuityPresentValue + presentValue;
            Mode = "SBPV";

        }

        public void OnPostYTDDone()
        {
            CalcInflow calcInflow = new CalcInflow(0, ACR, 0, numberOfPaymentsPerYear);
            double realRate = calcInflow.EAR;
            double cuponPayment = realRate * BFV;
            double cuponPayment_2 = ACR * BFV;
            YTM = (cuponPayment + ((BFV - currentBondPrice) / YtM)) / ((BFV + currentBondPrice) / 2);
            YTM = Math.Round(YTM * 100, 4);
            YTM_2 = (cuponPayment_2 + ((BFV - currentBondPrice) / YtM)) / ((BFV + currentBondPrice) / 2);
            YTM_2 = Math.Round(YTM_2 * 100, 4);
            Mode = "ETD";
        }
    }
}

Pages/DetailedCompounding.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CorporateFinance.Pages
{
    public class DetailedCompoundingModel : PageModel
    {
        public List<perPeriod> ca = new List<perPeriod> {
            new perPeriod(0, 0, 0)
            };

        [BindProperty]
        public double C { get; set; }
        [BindProperty]
        public double R { get; set; }
        [BindProperty]
        public double N { get; set; }
        [BindProperty]
        public int payments { get; set; }

        public string rett { get; set; }
        public string EAR { get; set; }


        public void OnGet(double R, double N, double C, int payments)
        {
            if (C == 0 || R == 0 || C == 0)
            {
                rett = "FV result will be desplayed here";
                EAR = "EAR will be desplayed here";
            }
            else
            {
               
                double realInterest = R / payments;
                double realPeriods = payments * N;
                
                CalcInflow calcInflow = new CalcInflow(C, R, N, payments);
                double a = Math.Round(Convert.ToDouble(calcInflow.res),2);
                rett = Convert.ToString(a);

                EAR = Convert.ToString(Math.Round(calcInflow.EAR,6));
                double y;
                int year;
                int currentPayment;
                for (int i = 1; i <= realPeriods; i++)
                {
                    y = C * Math.Pow((1 + realInterest), i);
                    y = Math.Round(y, 4);
                    year = (int)Math.Floor(Convert.ToDouble(i/payments));
                    year =year + 1;
                    currentPayment = (i + payments)%payments;
                    ca.Add(new perPeriod(currentPayment, y, year));

                }

            }
            
            
            
        }

        public void OnPost(double R, double N, double C, double payments)
        {         


        }
    }
}

Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace CorporateFinance.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace CorporateFinance.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        [BindProperty]
        public string Title { get; set; }

        
        public void OnGet()
        {
            Title = "We are doing it!";
        }

        public void OnPost(string Title)
        {
            
            
        }
    }
}

Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace CorporateFinance.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/StockData.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ServiceStack;
using System.Data;
using System.Configuration;
using System.Data.SqlClient;

namespace CorporateFinance
{
    public class StockDataModel : PageModel
    {
        [BindProperty]
        public string Ticker { get; set; }
        public List<AlphaVantageData> monthlyPrices = new List<AlphaVantageData> { new AlphaVantageData { High = 0, Low = 0, Close = 0, Open = 0, Timestamp = new DateTime(), Volume = 0 }
        };
        public IActionResult OnGet()
        {
            
            return Page();
        }

        
        public ActionResult DownloadReport()
        {
            
            var sb = new StringBuilder();
            foreach (var data in monthlyPrices)
            {
                sb.AppendLine(Convert.ToString(data.Timestamp) + ", " + data.Open + ", "+data.High+", "+data.Low+", "+data.Volume);
            }
            return File(new UTF8Encoding().GetBytes(sb.ToString()), "text/csv", "export.csv");
        }

        public void OnPost()
        {
            try
            {
                var symbol = Ticker;
                var apiKey = "VHIWZSYMEX1PFIU4";
                monthlyPrices = $"https://www.alphavantage.co/query?function=TIME_SERIES_MONTHLY&symbol={symbol}&apikey={apiKey}&datatype=csv"
                                .GetStringFromUrl().FromCsv<List<AlphaVantageData>>();

            }
            catch (Exception)
            {
                monthlyPrices = new List<AlphaVantageData> { new AlphaVantageData { High = 99999, Low = 99999, Close = 999999, Open = 99999, Timestamp = new DateTime(), Volume = 0 } };


            }
            
            

        }
    }
}

Pages/StockValuation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CorporateFinance
{
    public class StockValuationModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/fincators.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CorporateFinance
{
    public class fincatorsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Bonds.cshtml
@page
@model CorporateFinance.BondsModel
@{
    ViewData["Title"] = "Bond Calculations";
}

    <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="submit" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Calculator
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" asp-page-handler="Simple">Simple Bond Present Value</a>
            <a class="dropdown-item" asp-page-handler="ETD">Yield to Maturity (YTM)</a>
            <a class="dropdown-item" asp-page-handler="BondVal">Bond Valuation</a>

        </div>
    </div>

@if (Model.Mode == "SBPV")
{

    <div class="container">
        <h1>Simple Bond Present Value</h1>
        <form method="post" asp-page-handler="SimpleDone">
            <div class="form-group">
                <label for="ParValue">Par Value</label>
                <input type="text" class="form-control" id="ParValue" name="ParValue">
                <small id="emailHelp" class="form-text text-muted">
                    a.k.a. Face Value, The principal amount of a bond that is repaid at the end of the term.
                </small>
            </div>
            <div class="form-group">
                <label for="CouponRate">Coupon Rate (1% = 0.01)</label>
                <input type="text" class="form-control" id="CouponRate" name="CouponRate">
                <small id="emailHelp" class="form-text text-muted">
                    The annual coupon divided by the face value of a bond.
                </small>
            </div>
            <div class="form-group">
                <label for="DiscountRate">Dicount Rate/Yield to maturity (1% = 0.01)</label>
                <input type="text" class="form-control" id="DiscountRate" name="DiscountRate">
                <small id="emailHelp" class="form-text text-muted">
                    Rate of an alternative investment.
                </small>
            </div>
            <div class="form-group">
                <label for="YearsToMaturity">Years to maturity</label>
                <input type="text" class="form-control" id="YearsToMaturity" name="YearsToMaturity">

            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        <br />


        <h2>Bond Present Value:</h2>
        <div class="d-inline p-2 bg-primary text-white">
            $@Model.BondValue
        </div>

        <h2>Present value of the final payment:</h2>

        <div class="d-inline p-2 bg-primary text-white">
            $@Model.ParPV
        </div>

        <h2>Annuity present value:</h2>
        <div class="d-inline p-2 bg-primary text-white">
            $@Model.AnuPV
        </div>
    </div>
}



@if (Model.Mode == "ETD")
{
    <div class="container">
        <h1>Yield to Maturity (YTM)</h1>
        <form method="post" asp-page-handler="YTDDone">
            <div class="form-group">
                <label for="currentBondPrice">Current Bond Trading Price ($)</label>
                <input type="text" class="form-control" id="currentBondPrice" name="currentBondPrice">

            </div>
            <div class="form-group">
                <label for="BFV">Bond Face Value/Par Value ($)</label>
                <input type="text" class="form-control" id="BFV" name="BFV">

            </div>
            <div class="form-group">
                <label for="YtM">Years to Maturity</label>
                <input type="text" class="form-control" id="YtM" name="YtM">

            </div>
            <div class="form-group">
                <label for="ACR">Annual Coupon Rate (%), 1% = 0.01</label>
                <input type="text" class="form-control" id="ACR" name="ACR">

            </div>
            <div class="form-group">
                <label for="numberOfPaymentsPerYear">Number of Payments Per Year</label>
                <input type="text" class="form-control" id="numberOfPaymentsPerYear" name="numberOfPaymentsPerYear">

            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>

        <br />


        <h2>YTM</h2>
        <div>
            <h5>EAR Enabled</h5>
            <div class="d-inline p-2 bg-primary text-white">
                @Model.YTM%
            </div>
        </div>
        <br />

        <div>
            <h5>EAR Disabled</h5>
            <div class="d-inline p-2 bg-primary text-white">
                @Model.YTM_2%
            </div>
        </div>





    </div>
}

Pages/DetailedCompounding.cshtml
@page
@model CorporateFinance.Pages.DetailedCompoundingModel
@{
    ViewData["Title"] = "Detailed Compounding";
}

<h1>
    EFFECTIVE ANNUAL RATES AND COMPOUNDING
</h1>
<form>
    <div class="form-group">
        <label for="C">Initial Investment</label>
        <input type="text" class="form-control" name="C" id="C" placeholder="C">

    </div>
    <div class="form-group">
        <label>% return per year (APR)</label>
        <input type="text" class="form-control" name="R" placeholder="R, 0.01 = 1%" id="exampleInputPassword1">
    </div>
    <div class="form-group">
        <label>Num of payments per year</label>
        <input type="text" class="form-control" name="payments" placeholder="Number of payments per period" id="exampleInputPassword1">
    </div>
    <div class="form-group">
        <label>Number of years</label>
        <input type="text" class="form-control" name="N" placeholder="N" id="exampleInputPassword1">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>
<label>FV</label>
<div class="shadow-lg p-3 mb-5 bg-white rounded">@Model.rett</div>
<label>EAR</label>
<div class="shadow-lg p-3 mb-5 bg-white rounded">@Model.EAR</div>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Year</th>
            <th scope="col">Payment in year</th>
            <th scope="col">Amount</th>
            
            
        </tr>
    </thead>
    <tbody>
        @foreach (var d in @Model.ca)
        {
            <tr>
                <td>@d.year</td>
                <td>@d.index</td>
                <td>$@d.res</td>
                
            </tr>


        }

    </tbody>
</table>

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}




    <div class="card text-center">
        <div class="card-header">
            Welcome
        </div>
        <div class="card-body">
            <h5 class="card-title">The only corporate finance website you will ever need.</h5>
            <p class="card-text">Made by Kiril Spiridonov (Kairo)</p>
            <a asp-page="/DetailedCompounding" class="btn btn-primary">Some Calculations</a>
        </div>
        <div class="card-footer text-muted">
            <div class="w-25 p-3" style="width: 800px; margin: 0 auto;">
                <a href="https://github.com/kiko1004">
                <img src="https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png" class="img-thumbnail" height="80" width="80">
                </a>
                
                <a href="https://www.linkedin.com/in/kiril-spiridonov-916326149/">
                    <img src="https://cdn4.iconfinder.com/data/icons/social-media-icons-the-circle-set/48/linkedin_circle-512.png" height="80" width="80" class="img-thumbnail">
                </a>

            </div>


            </div>
    </div>



    @*<div class="text-center">
            <h1>@Model.Title</h1>
        </div>

        <form method="post">
            <div class="form-group">
                <label for="Title">Title</label>
                <input type="text" class="form-control" id="Title" name="Title" placeholder="Title">
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>*@

Pages/StockData.cshtml
@page
@model CorporateFinance.StockDataModel
@{
    ViewData["Title"] = "Detailed Compounding";
}

<form method="post">
    <div class="form-group">
        <label for="Ticker">Ticker</label>
        <input type="text" class="form-control" id="Ticker" name="Ticker" placeholder="MSFT">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>




<table class="table">
    <thead>
        <tr>
            <th scope="col">Date</th>
            <th scope="col">Open</th>
            <th scope="col">High</th>
            <th scope="col">Low</th>
            <th scope="col">Close</th>
            <th scope="col">Volume</th>


        </tr>
    </thead>
    <tbody>
        @foreach (var d in @Model.monthlyPrices)
        {
        <tr>
            <td>@d.Timestamp</td>
            <td>@d.Open</td>
            <td>@d.High</td>
            <td>@d.Low</td>
            <td>@d.Close</td>
            <td>@d.Volume</td>



        </tr>


        }

    </tbody>
</table>

Pages/StockValuation.cshtml
@page
@model CorporateFinance.StockValuationModel
@{
    ViewData["Title"] = "Stock Valuation";
}

Pages/fincators.cshtml
@page
@model CorporateFinance.fincatorsModel
@{
    ViewData["Title"] = "Fincators";
}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <h2>
                <span class="fontstyle0">Ratio Analysis</span>
            </h2>
            <p>
                <span class="fontstyle0">Financial ratios are the</span> <span class="fontstyle2">Relationships determined from a firm’s financial information and used for comparison purposes.</span> Such ratios are ways of comparing and investigating the relationships between different pieces of financial information. Using ratios <span>eliminates the size problem because the size effectively divides out. We’re then left with</span> <span>percentages, multiples, or time periods.</span> <span>There is a problem in discussing financial ratios. Because a ratio is simply one number</span> <span>divided by another, and because there are so many accounting numbers out there, we could</span> <span>examine a huge number of possible ratios. Everybody has a favorite. We will restrict ourselves to a representative sampling.</span>
            </p>
            <p>
                <a class="btn" href="#"></a>
            </p>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <h4 style="color:aqua;">Return on Assets</h4>
            <p><var>ROA</var> = <sup><var>Net income</var></sup>&frasl; <sub><var>Total assets</var></sub></p>
            <h4 style="color:aqua;">Return on Equity</h4>
            <p><var>ROE</var> = <sup><var>Net income</var></sup>&frasl; <sub><var>Total equity</var></sub></p>
            <h4 style="color:aqua;">Earnings per share</h4>
            <p><var>EPS</var> = <sup><var>Net income</var></sup>&frasl; <sub><var>Shares outstanding</var></sub></p>
            <h4 style="color:aqua;">Price-Earnings Ratio</h4>
            <p><var>PE ratio</var> = <sup><var>Price per share</var></sup>&frasl; <sub><var>Earnings per share</var></sub></p>

            <h4>Current Ratio</h4>
            <p><var>Current ratio</var> = <sup><var> Current assets</var></sup>&frasl;<sub><var> Current Liabilities</var></sub></p>
            <h4>Quick Ratio</h4>
            <p><var>Quick ratio</var> = <sup><var> Current assets</var> - <var>Inventory</var></sup>&frasl; <sub><var> Current Liabilities</var></sub></p>
            <h4>Cash Ratio</h4>
            <p><var>Cash ratio</var> = <sup><var>Cash</var></sup>&frasl; <sub><var> Current Liabilities</var></sub></p>
            <h4>Net working capital to total assets</h4>
            <p><var>NWCtTA</var> = <sup><var>Net working capital to total assets</var></sup>&frasl; <sub><var> Total Assets</var></sub></p>
            <h4>Interval measure</h4>
            <p><var>IM</var> = <sup><var>Current assets</var></sup>&frasl; <sub><var>Average daily operating costs</var></sub></p>
            <h4>Total debt ratio</h4>
            <p><var>Total debt ratio</var> = <sup><var>Total assets - Total equity</var></sup>&frasl; <sub><var>Total assets</var></sub></p>
            <h4>Debt–equity ratio</h4>
            <p><var>Debt–equity ratio</var> = <sup><var>Total debt</var></sup>&frasl; <sub><var>Total equity</var></sub></p>
            <h4>Equity multiplier</h4>
            <p><var>Equity multiplier</var> = <sup><var>Total assets</var></sup>&frasl; <sub><var>Total equity</var></sub></p>
            <h4>Long-term debt ratio</h4>
            <p><var>Long-term debt ratio</var> = <sup><var>Long-term debt</var></sup>&frasl; <sub><var>Long-term debt + Total equity</var></sub></p>
            <h4>Profit margin</h4>
            <p><var>Profit margin</var> = <sup><var>Profit margin</var></sup>&frasl; <sub><var>Sales</var></sub></p>

        </div>
    </div>
</div>